import java.util.Scanner;
import greeting.*;
public class BankManager
{
	String name;
	int accno;
	int balance;
	static int x=2;
	void incre()
	{
		x++;
	}
	static void dispcount()
	{
		System.out.println("The total number of permanent customers are:"+x);
	}
	
		
	static
	{
		System.out.println("Welcome to Bank\n");
	}
	
	{
		
		System.out.println("Customers are created");
	}
	
	BankManager(String name,int accno,int balance)
	{
			this.name=name;
			this.accno=accno;
			this.balance=balance;
	}
	BankManager(String a,int b)
	{
		    name=a;
			accno=b;
	}
	BankManager()
	{}
	
	
	void getDetails(int n)
	{
		System.out.println("Enter your name ");
		Scanner input=new Scanner(System.in);
		name=input.next();
		accno=1000+n;
		System.out.println("Your autogenerated account number is"+accno+"\n");
	}
	void display()
	{
		System.out.println("Name: "+name+"\tAccno: "+accno+"\tBalance: "+balance);
	}
	void deposit()
	{
		System.out.println("How much do you want to deposit?");
		Scanner input = new Scanner(System.in);
		int d=input.nextInt();
		int x=balance+d;
		System.out.println("Name:"+name+"\tAccNo:" + accno +"\t Old balance: "+balance+"\t Amount credited:"+d+" \tNew Balance: "+x+"\nTransaction successful");
		balance=balance+d;
	}
	void withdraw()
	{
		System.out.println("How much do you want to withdraw? ");
		Scanner input=new Scanner(System.in);
		int w=input.nextInt();
		
		if(w>balance)
		{
			System.out.println("Name: "+name+"\t Account Number: "+accno+"\tOld Balance: "+balance+"\tNew Balance: "+balance);
			System.out.println("No enough balance. Request could not be processed\n ");
			
		}
		else
		{
			int y=balance-w;
			System.out.println("Name: "+name+"\tAccount Number: "+accno+"\t Old Balance: "+balance+"\tAmount debited: "+w+"\tNew Balance: "+y+"\nWithdraw successful");
			balance=balance-w;
		}
	}
	int search(int x)
	{
		if(accno==x)
			return 1;
		else
			return 0;
	}
	
	public static void main(String[] args)
	{
		BankManager[] b=new BankManager[10];
		Thanks t=new Thanks();
	
		int ch=1,count=3,ch1=8,r,i,count1=2;
		b[0]= new BankManager("Saran",500,20000);
		b[1]=new BankManager("Kumar",1000,15000);
		b[2]=new BankManager();
		b[3]=new BankManager();
		b[4]=new BankManager();
		b[5]=new BankManager();
		b[6]=new BankManager();
		b[7]=new BankManager();
		b[8]=new BankManager();
		b[9]=new BankManager();
		while(ch!=0)
		{
			System.out.println("Enter the choice: 1.Create new account 2.Display all details\n 4.Deposit 5.Withdraw 6.Count of cutomers 0.Exit ");
			Scanner input=new Scanner(System.in);
			ch=input.nextInt();
			switch(ch)
			{
				case 1:
				i=2;
				while(ch1!=0)
				{	
					b[i].getDetails(i);
					b[i].incre();
					i++;
					System.out.println("Enter 1 to add new customer and 0 to exit");
					ch1=input.nextInt();
				}
				 count1=i;
				break;
			
				case 2:
				for(i=0;i<count1;i++)
				{b[i].display();
				}
				break;
					
					
				case 4:
				
				System.out.println("Enter the account number to deposit:");
				r=input.nextInt();
				for(i=0;i<6;i++)
				{
					if((b[i].search(r))==1)
					{b[i].deposit();break;}
					
				}
				break;
				case 5:
				System.out.println("Enter the account number to withdraw:");
				r=input.nextInt();
				for(i=0;i<6;i++)
				{
					if(b[i].search(r)==1)
					{b[i].withdraw();break;}
						
				}
				break;
				
				/*case 3:
				System.out.println("Enter the account number to make permanent :");
				r=input.nextInt();
				
				for(i=0;i<6;i++)
				{
					if(b[i].search(r)==1)
					{b[i].incre();
					break;}
						
				}
				break;*/
				case 6:
				dispcount();
				break;
				
			}
		}
				
	}
}
	
	